=== JuanjoSalva/P-gina-xsl/HTML/LEGAL/legal.dtd
<!ELEMENT pagina (cabecera, cuerpo, pie)>
	<!ELEMENT  cabecera (titulo, texto1)>
			<!ELEMENT titulo (#PCDATA)>
			<!ELEMENT texto1 (#PCDATA)>		
	<!ELEMENT  cuerpo (calle, cp, localidad?, provincia, telefono*, fila*)>
			<!ELEMENT calle (#PCDATA)>
			<!ELEMENT cp (#PCDATA)>
			<!ELEMENT localidad (#PCDATA)>
			<!ELEMENT provincia (#PCDATA)>
			<!ELEMENT telefono (#PCDATA)>
			<!ELEMENT fila (txt*)>
				<!ELEMENT txt (#PCDATA)>
<!ELEMENT pie (link?, mail)>
		<!ELEMENT link (ruta, texto)>
			<!ELEMENT ruta (#PCDATA)>
			<!ELEMENT texto (#PCDATA)>
		<!ELEMENT mail (correo, asunto)>
			<!ELEMENT correo (#PCDATA)>
			<!ELEMENT asunto (#PCDATA)>

=== JuanjoSalva/P-gina-xsl/HTML/LEGAL/legal.xml
<?xml version="1.0" encoding ="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href= "legal.xsl"?>
<!DOCTYPE pagina SYSTEM "legal.dtd">
 
<pagina>
	<cabecera>
		<titulo>
			AVISO LEGAL
		</titulo>
		
		<texto1>
			ESCUELA INFANTIL DUENDES
		</texto1>
	</cabecera>
	
	<cuerpo>
		<calle>
			C/ LA HUERTA Nº 7 BAJO
		</calle>
		
		<cp>
			03690
		</cp>
		
		<localidad>
			SAN VICENTE DEL RASPEIG
		</localidad>
		
		<provincia>
			ALICANTE
		</provincia>
		
		<telefono>
			679473537
		</telefono>
		
		<telefono>
			636381442
		</telefono>
		
		<telefono>
			965049772
		</telefono>
		
		<fila>	
			<texto>
				<txt>				
					Aviso Legal 
				</txt>
			</texto>
		</fila>
		
		<fila>
			<texto>
				<txt>
					Información General
				</txt>
			</texto>
		
			<texto>
				<txt>	
					En cumplimiento del artículo 10 de la Ley 34/2002, del 11 de julio, de servicios de la Sociedad de la Información y Comercio Electrónico (LSSICE) se exponen a continuación los datos identificativos de la empresa.
				</txt>
			</texto>
		
			<texto>
				<txt>	
					Denominación social: Escuela Infantil Duendes
				</txt>
			
				<txt>	
					Número de identificación fiscal: CIF: B54551387 
				</txt>
			
				<txt>	
					Domicilio social: Calle la Huerta 7 03690 San Vicente del Raspeig
				</txt>
			
				<txt>	
					Correo electrónico: informacion@duendesdesanvicente.es  
				</txt>
			
				<txt>	
					Teléfono: 679473537 
				</txt>
				
				<txt>
					636381442
				</txt>
			</texto>
			
			<texto>
				<txt>
				Este sitio web ha sido creado por la empresa "Escuela Infantil Duendes" con carácter informativo y para uso personal de los usuarios. A través de este Aviso legal, se pretende regular el acceso y uso de este sitio web, así como la relación entre el sitio web y sus usuarios.
				</txt>
			
				<txt>
				El simple acceso a este sitio web no supone entablar ningún tipo de relación comercial entre "Escuela Infantil Duendes" y el usuario.
				</txt>
			
				<txt>
				El acceso a este sitio web es responsabilidad exclusiva de los usuarios. El acceso y la navegación en este sitio web supone aceptar y conocer las advertencias legales, condiciones y términos de uso contenidas en ella.
				</txt>
			</texto>
			
		</fila>
		
		<fila>
			<texto>
				<txt>
					Propiedad Intelectual y uso de los contenidos
				</txt>
			</texto>
		
			<texto>
				<txt>
					El código fuente, los diseños gráficos, las imágenes, las fotografías, los sonidos, las animaciones, el software, los textos, así como la información y los contenidos que se recogen en "www.duendesdesanvicente.es", están protegidos por la legislación española sobre los derechos de propiedad intelectual e industrial a favor de "Escuela Infantil Duendes." y no se permite la copia, reproducción y/o publicación, total o parcial, del sitio web ni de cualquiera de sus contenidos, ni su tratamiento informático, su distribución, su difusión, ni su modificación o transformación ni demás derechos reconocidos legalmente a su titular, sin el permiso previo y por escrito del mismo, de "Escuela Infantil Duendes".
				</txt>
				
				<txt>
					Quedan a salvo de lo anterior los derechos derivados de la propiedad industrial y de la propiedad intelectual, propiedad de terceras personas, físicas o jurídicas, que por cualquier circunstancia se hallasen en "www.duendesdesanvicente.es".
				</txt>
				
				<txt>
					El usuario, única y exclusivamente, puede utilizar el material que aparezca en este sitio web para su uso personal y privado, excepto en aquellos casos en que se especifique claramente lo contrario, quedando prohibido de forma general su uso con fines comerciales o para incurrir en actividades ilícitas. Todos los derechos derivados de la propiedad intelectual están expresamente reservados por "Escuela Infantil Duendes".			
				</txt>
			</texto>
			
			<texto>
				<txt>
					"Escuela Infantil Duendes" velará tanto por el cumplimiento de las anteriores condiciones como por la debida utilización de los contenidos presentados en su sitio web, ejercitando todas las acciones civiles y penales que le correspondan en el caso de infracción o incumplimiento de estos derechos por parte del usuario.
				</txt>
				
				<txt>
					"Escuela Infantil Duendes" se reserva el derecho a modificar cualquier tipo de información que pudiera aparecer en el sitio web, así como su configuración y presentación, sin que exista obligación de preavisar o poner en conocimiento de los usuarios dichas obligaciones, entendiéndose como suficiente con la publicación en el sitio web del "Escuela Infantil Duendes".
				</txt>
				
				<txt>
					"Escuela Infantil Duendes" se compromete a través de este medio a NO REALIZAR PUBLICIDAD ENGAÑOSA. A estos efectos, por lo tanto, no serán considerados como publicidad engañosa los errores formales o numéricos que puedan encontrarse a lo largo del contenido de las distintas secciones de la web de "Escuela Infantil Duendes", producidos como consecuencia de un mantenimiento y/o actualización incompleta o defectuosa de la información contenida es estas secciones. "Escuela Infantil Duendes", como consecuencia de lo dispuesto en este apartado, se compromete a corregirlo tan pronto como tenga conocimiento de dichos errores.
				</txt>
				
				<txt>
					"Escuela Infantil Duendes" se compromete a NO REMITIR COMUNICACIONES COMERCIALES SIN IDENTIFICARLAS COMO TALES, conforme a lo dispuesto en la Ley 34/2002 de Servicios de la Sociedad de la Información y de comercio electrónico. A estos efectos no será considerado como comunicación comercial toda la información que se envíe A LOS CLIENTES "Escuela Infantil Duendes" siempre que tenga por finalidad el mantenimiento de la relación contractual existente entre cliente y "Escuela Infantil Duendes", así como el desempeño de las tareas de información, formación y otras actividades propias del servicio que el cliente tiene contratado con la empresa.
				</txt>
				
				<txt>
					El sitio web de "Escuela Infantil Duendes" puede utilizar cookies (pequeños archivos de información que el servidor envía al ordenador de quien accede a la página) para llevar a cabo determinadas funciones que son consideradas imprescindibles para el correcto funcionamiento y visualización del sitio. Las cookies utilizadas en el sitio web tienen, en todo caso, carácter temporal con la única finalidad de hacer más eficaz la siguiente transmisión y desaparecen al terminar la sesión del usuario. En ningún caso se utilizarán las cookies para recoger información de carácter personal.
				</txt>
				
				<txt>
					Cuando el usuario se encuentre navegando por las páginas web de "Escuela Infantil Duendes" el servidor donde se encuentra alojada reconoce automáticamente la dirección IP de su ordenador, el día y la hora en la que comienza la visita, en la que abandona la visita, así como información sobre las distintas secciones consultadas. Es necesario que el servidor conozca estos datos para poder comunicarse y enviarle la petición realizada y que a través del navegador se pueda ver en la pantalla.
				</txt>
			</texto>
		</fila>
		
		<fila>
			<texto>
				<txt>
					Protección de datos de carácter personal
				</txt>
			</texto>
			
			<texto>
				<txt>
					En el marco del cumplimiento de la legislación vigente, recogida en la Ley Orgánica 15/1999, de 13 de diciembre, sobre protección de Datos de Carácter Personal (LOPD), cuyo objeto es garantizar y proteger, en lo que concierne al tratamiento de los datos personales, las libertades y derechos fundamentales de las personas físicas, y especialmente de su honor e intimidad personal, "Escuela Infantil Duendes" informa a los usuarios que como responsable del tratamiento, le garantiza la posibilidad de ejercitar sus derechos de acceso, rectificación, 					
				</txt>
				
				<txt>
					cancelación y oposición al tratamiento de sus datos, dirigiendo una comunicación por escrito a la dirección indicada anteriormente o bien 
				</txt>
				
				<txt>
					a informacion@duendesdesanvicente.es . 
				</txt>
			</texto>
			
		</fila>
		
		<fila>
			<texto>
				<txt>
					Exclusión de garantías y Responsabilidad
				</txt>
				
				<txt>
					1."Escuela Infantil Duendes" no garantiza el funcionamiento de www.duendesdesanvicente.es ni de sus contenidos y servicios, ya pertenezcan al propio sitio web o a terceros, ni que sean útiles para la realización de algún particular fin o actividad, ni que se hallen libres de virus informáticos, por lo que no es responsable de eventuales daños y perjuicios que puedan producirse por su uso.
				</txt>			
		
				<txt>
					2."Escuela Infantil Duendes" se exime de cualquier tipo de responsabilidad derivada de la información publicada en su sitio web, siempre que esta información haya sido manipulada o introducida por un tercero ajeno al mismo.
				</txt>			
		
				<txt>		 
					 3.Cualquier enlace no implica por sí solo la existencia de una relación con "Escuela Infantil Duendes" ni que ésta conozca todos los contenidos o servicios que se muestren en el lugar en donde se hallen. 
				</txt>			
			
				<txt>		 
					 4.Desde el sitio web de "Escuela Infantil Duendes" es posible que se redirija, o se enlace, a contenidos de otros sitios web. Dado que "Escuela Infantil Duendes" no puede controlar siempre los contenidos introducidos por los terceros en sus sitios web, éste no asume ningún tipo de responsabilidad respecto a dichos contenidos. En todo caso, el prestador manifiesta que procederá a la retirada inmediata de cualquier contenido que pudiera contravenir la legislación nacional o internacional, la moral o el orden público, procediendo a la retirada inmediata de la redirección y/o enlace a dicho sitio web, poniendo en conocimiento de las autoridades competentes el contenido en cuestión.
				</txt>			
			
				<txt>
