=== JuanjoSalva/P-gina-xsl/_vti_txt/HTML/CONTACTAR/contacta.dtd
<!ELEMENT pagina (cabecera, cuerpo,pie)>
	<!ELEMENT cabecera (titulo?)>
		<!ELEMENT titulo (#PCDATA)>
	<!ELEMENT cuerpo (rotulo?,calle?, localidad?,provincia,telefono*)>
		<!ELEMENT rotulo (#PCDATA)>
		<!ELEMENT calle (#PCDATA)>
		<!ELEMENT localidad (#PCDATA)>
		<!ELEMENT provincia (#PCDATA)>
		<!ELEMENT telefono (#PCDATA)>
	<!ELEMENT pie (correo*)>
		<!ELEMENT correo (#PCDATA)>

=== JuanjoSalva/P-gina-xsl/_vti_txt/HTML/CONTACTAR/contacta.xml
<?xml version="1.0" encoding ="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href= "contacta.xsl"?>
<!DOCTYPE pagina SYSTEM "contacta.dtd">
 
<pagina>
	<cabecera>
		<titulo>CONTACTAR</titulo>
	</cabecera>
	
	<cuerpo>
		<rotulo>
			ESCUELA INFANTIL DUENDES
		</rotulo>
		
		<calle>
			C/ LA HUERTA Nº 7 BAJO
		</calle>
		
		<localidad>
			03690        SAN VICENTE DEL RASPEIG
		</localidad>
		
		<provincia>
			ALICANTE
		</provincia>
		
		<telefono>
			679473537
		</telefono>
		
		<telefono>
			636381442
		</telefono>
		
		
	</cuerpo>
	
    <pie>
		<correo>
			informacion@duendesdesanvicente.com
		</correo>
	</pie>
</pagina>
