=== JuanjoSalva/P-gina-xsl/cgi-bin/BTT/HTML/HTML/REGISTRO/Registro.dtd
<!ELEMENT pagina (cabecera,cuerpo,pie)>
	<!ELEMENT cabecera (titulo)>
		<!ELEMENT titulo (#PCDATA)>
		
		
	<!ELEMENT cuerpo (nombre, apellido1, apellido2, email, telefono, sexo, usuario, contra)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT apellido1 (#PCDATA)>
		<!ELEMENT apellido2 (#PCDATA)>
		<!ELEMENT email (#PCDATA)>
		<!ELEMENT telefono (#PCDATA)>
		<!ELEMENT sexo (#PCDATA)>
		<!ELEMENT usuario (#PCDATA)>
		<!ELEMENT contra (#PCDATA)>		
		
	<!ELEMENT pie (link1, link2, boton1, boton2)>
		<!ELEMENT link1 (#PCDATA)>
		<!ELEMENT link2 (#PCDATA)>
		<!ELEMENT boton1 (#PCDATA)>
		<!ELEMENT boton2 (#PCDATA)>

=== JuanjoSalva/P-gina-xsl/cgi-bin/BTT/HTML/HTML/REGISTRO/Registro.xml
<?xml version="1.0" encoding ="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href= "Registro.xsl"?>
<!DOCTYPE pagina SYSTEM "Registro.dtd">
 
<pagina>
	<cabecera>
			<titulo>REGISTRO</titulo>
	</cabecera>
	
	<cuerpo>
		<nombre>Nombre:</nombre>
		<apellido1>Primer Apellido:</apellido1>
		<apellido2>Segundo Apellido:</apellido2>
		<email>Email::</email>
		<telefono>Teléfono:</telefono>
		<sexo>Sexo:</sexo>
		<usuario>Usuario:</usuario>
		<contra>Contraseña</contra>
	</cuerpo>
	
    <pie>
		<link1>Volver al Principio</link1>
		<link2>Inicio</link2>
		<Boton1>OK</Boton1>		
		<Boton2>Borrar Datos</Boton2>		
	</pie>
</pagina>
