=== JuanjoSalva/P-gina-xsl/cgi-bin/BTT/HTML/HTML/PLAN/plan.dtd
<!ELEMENT arbol (ruta*)>
<!ELEMENT ruta (fecha, nombre, pais, ciudad, localidad, dificultad, distancia, altitud_min, altitud_max, desnivel_acum_subiendo, desnivel_acum_bajando, mapa?, imagen?)>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT dificultad (#PCDATA)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT altitud_min (#PCDATA)>
<!ELEMENT altitud_max (#PCDATA)>
<!ELEMENT desnivel_acum_subiendo (#PCDATA)> 
<!ELEMENT desnivel_acum_bajando (#PCDATA)>
<!ELEMENT mapa (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>

=== JuanjoSalva/P-gina-xsl/cgi-bin/BTT/HTML/HTML/PLAN/plan.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="plan.xsl"?>
<!DOCTYPE arbol SYSTEM "plan.dtd">
<arbol>
  
  <ruta>
    <fecha_prev>12/06/2011</fecha_prev>
	<fecha_inscrip>06/09/2010</fecha_inscrip>
    <nombre>Camino de Santiago</nombre>
    <pais>España</pais>
    <ciudad>Santiago</ciudad>
    <localidad>Santiago</localidad>
    <dificultad>Alta</dificultad>
    <distancia>402.42 Km</distancia>
    <altitud_min>500 metros</altitud_min>
    <altitud_max>1.825 metros</altitud_max>
    <desnivel_acum_subiendo> 800 metros</desnivel_acum_subiendo>
    <desnivel_acum_bajando> 1200 metros</desnivel_acum_bajando>
    <mapa>Mapa/SantiagoPrimitivo.jpg </mapa> <!-- Mapa de localización, googlemaps -->
    <imagen>Imagen/SantiagoPrimitivo.jpg </imagen>  <!-- Imagen de desnivel -->
  </ruta>
  
</arbol>
