=== JuanjoSalva/P-gina-xsl/cgi-bin/BTT/HTML/HTML/RUTAS/TipoRuta.dtd
<!ELEMENT pagina (cabecera,cuerpo,pie)>
	<!ELEMENT cabecera (titulo, texto)>
		<!ELEMENT titulo (#PCDATA)>
		<!ELEMENT texto (#PCDATA)>
		
	<!ELEMENT cuerpo (ruta*)>
		<!ELEMENT ruta (nombre,mapa,texto1,imagen,grado,distancia,altitud_min,altitud_max,des_sub,des_baj)>
			<!ELEMENT nombre (#PCDATA)>
			<!ELEMENT mapa (#PCDATA)>
			<!ELEMENT texto1 (#PCDATA)>
			<!ELEMENT imagen (#PCDATA)>
			<!ELEMENT grado (#PCDATA)>
			<!ELEMENT distancia (#PCDATA)>
			<!ELEMENT altitud_min (#PCDATA)>
			<!ELEMENT altitud_max (#PCDATA)>
			<!ELEMENT des_sub (#PCDATA)>
			<!ELEMENT des_baj (#PCDATA)>
		
	
	<!ELEMENT pie (link1, link2)>
		<!ELEMENT link1 (#PCDATA)>
		<!ELEMENT link1 (#PCDATA)>

=== JuanjoSalva/P-gina-xsl/cgi-bin/BTT/HTML/HTML/RUTAS/RutasMedio.xml
<?xml version="1.0" encoding ="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href= "TipoRuta.xsl"?>
<!DOCTYPE pagina SYSTEM "TipoRuta.dtd">
 
<pagina>
	<cabecera>
			<titulo>RUTAS DIFICULTAD MODERADA</titulo>
			<texto>Si se queire un poco de explicación, sino se puede borrar y dejar en blanco para un futuro.</texto>
	</cabecera>
	
	<cuerpo>
		<ruta>
			<nombre>RUTAS DE LAS ZORRILAS(GIBALBÍN)</nombre>
			<mapa>Imagen/Medio/Mapa/LasZorrillas.bmp</mapa>
			<texto1>cerca de Las Navas, Andalucía (España) </texto1>
			<imagen>Imagen/Medio/Desnivel/LasZorrilas.jpg</imagen>
			<grado>Moderado</grado>
			<distancia>30,42 km</distancia>
			<altitud_min>43 metros</altitud_min>
			<altitud_max>182 metros</altitud_max>
			<des_sub>371 metros</des_sub>
			<des_baj>381 metros</des_baj>
		</ruta>
		
		<ruta>
			<nombre>RUTAS POR MANCERA DE ABAJO</nombre>
			<mapa>Imagen/Medio/Mapa/Mancera.bmp</mapa>
			<texto1>cerca de Mancera de Abajo, Castilla y León (España) </texto1>
			<imagen>Imagen/Medio/Desnivel/Mancera.jpg</imagen>
			<grado>Moderado</grado>
			<distancia>61,82 km</distancia>
			<altitud_min>875 metros</altitud_min>
			<altitud_max>1.232 metros</altitud_max>
			<des_sub>649 metros</des_sub>
			<des_baj>664 metros</des_baj>
		</ruta>
	</cuerpo>
	
    <pie>
		<link1>Volver al Principio</link1>
		<link2>Inicio</link2>		
	</pie>
	
</pagina>

=== JuanjoSalva/P-gina-xsl/cgi-bin/BTT/HTML/HTML/RUTAS/RutasFacil.xml
<?xml version="1.0" encoding ="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href= "TipoRuta.xsl"?>
<!DOCTYPE pagina SYSTEM "TipoRuta.dtd">
 
<pagina>
	<cabecera>
			<titulo>RUTAS DIFICULTAD FÁCIL </titulo>
			<texto>Si se queire un poco de explicación, sino se puede borrar y dejar en blanco para un futuro.</texto>
	</cabecera>
	
	<cuerpo>
		<ruta>
			<nombre>RUTA DE RADIQUERO</nombre>
			<mapa>Imagen/Facil/Mapa/Radiquero.bmp</mapa>
			<texto1>Cerca de Radiquero, Aragón (España)</texto1>
			<imagen>Imagen/Facil/Desnivel/Radiquero.jpg</imagen>
			<grado>Fácil</grado>
			<distancia>20,93 km</distancia>
			<altitud_min>472 metros</altitud_min>
			<altitud_max>852 metros</altitud_max>
			<des_sub>478 metros</des_sub>
			<des_baj>508 metros</des_baj>
		</ruta>
		
		<ruta>
			<nombre>RUTA DE CIUDAD REAL-CALATRAVA</nombre>
			<mapa>Imagen/Facil/Mapa/Calatrava.bmp</mapa>
			<texto1>cerca de Ciudad Real, Castilla-La Mancha (España) </texto1>
			<imagen>Imagen/Facil/Desnivel/Calatrava.jpg</imagen>
			<grado>Fácil</grado>
			<distancia>33,67 km</distancia>
			<altitud_min>604 metros</altitud_min>
			<altitud_max>650 metros</altitud_max>
			<des_sub>79 metros</des_sub>
			<des_baj>87 metros</des_baj>
		</ruta>
	</cuerpo>
	
    <pie>
		<link1>Volver al Principio</link1>
		<link2>Inicio</link2>		
	</pie>
	
	
</pagina>

=== JuanjoSalva/P-gina-xsl/cgi-bin/BTT/HTML/HTML/RUTAS/RutasDificil.xml
<?xml version="1.0" encoding ="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href= "TipoRuta.xsl"?>
<!DOCTYPE pagina SYSTEM "TipoRuta.dtd">
 
<pagina>
	<cabecera>
			<titulo>RUTAS DIFICULTAD ALTA </titulo>
			<texto>Si se queire un poco de explicación, sino se puede borrar y dejar en blanco para un futuro.</texto>
	</cabecera>
	
	<cuerpo>
		<ruta>
			<nombre>CAMINO SANTIAGO PRIMITIVO </nombre>
			<mapa>Imagen/Dificil/Mapa/SantiagoPrimitivo.jpg</mapa>
			<texto1>Cerca de Arcos, Asturias (España)</texto1>
			<imagen>Imagen/Dificil/Desnivel/SantiagoPrimitivo.jpg</imagen>
			<grado>Dificil</grado>
			<distancia>317,35 km</distancia>
			<altitud_min>40 metros</altitud_min>
			<altitud_max>1.1225 metros</altitud_max>
			<des_sub>6.794 metros</des_sub>
			<des_baj>6.801 metros</des_baj>
		</ruta>
		
		<ruta>
			<nombre>SEVILLA LA NUEVA-CUERDA DE LA PARADA </nombre>
			<mapa>Imagen/Dificil/Mapa/CuerdaLaParada.bmp</mapa>
			<texto1>cerca de Sevilla La Nueva, Comunidad de Madrid (España) </texto1>
			<imagen>Imagen/Dificil/Desnivel/CuerdaLaParada.jpg</imagen>
			<grado>Difícil</grado>
			<distancia>74,41 km</distancia>
			<altitud_min>498 metros</altitud_min>
			<altitud_max>986 metros</altitud_max>
			<des_sub>1.328 metros</des_sub>
			<des_baj>1.368 metros</des_baj>
		</ruta>
	</cuerpo>
	
    <pie>
		<link1>Volver al Principio</link1>
		<link2>Inicio</link2>		
	</pie>
	
</pagina>

=== JuanjoSalva/P-gina-xsl/cgi-bin/BTT/HTML/HTML/RUTAS/RutasMuyDificil.xml
<?xml version="1.0" encoding ="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href= "TipoRuta.xsl"?>
<!DOCTYPE pagina SYSTEM "TipoRuta.dtd">
 
<pagina>
	<cabecera>
			<titulo>RUTAS DIFICULTAD MUY ALTA </titulo>
			<texto>Si se queire un poco de explicación, sino se puede borrar y dejar en blanco para un futuro.</texto>
	</cabecera>
	
	<cuerpo>
		<ruta>
			<nombre>CASTILLONROY </nombre>
			<mapa>Imagen/MuyDificil/Mapa/Castillonroy.bmp</mapa>
			<texto1>cerca de Castellonroi / Castillonroy, Aragón (España)  </texto1>
			<imagen>Imagen/MuyDificil/Desnivel/Castillonroy.jpg</imagen>
			<grado>Muy Alta</grado>
			<distancia>51,4 km</distancia>
			<altitud_min>335 metros</altitud_min>
			<altitud_max>1.082 metros</altitud_max>
			<des_sub>1.402 metros</des_sub>
			<des_baj>1.349 metros</des_baj>
		</ruta>
	</cuerpo>
	
    <pie>
		<link1>Volver al Principio</link1>
		<link2>Inicio</link2>		
	</pie>
	
</pagina>
