=== JuanjoSalva/P-gina-xsl/cgi-bin/BTT/HTML/HTML/INICIO/Inicio.dtd
<!ELEMENT pagina (cabecera,cuerpo,pie)>
	<!ELEMENT cabecera (titulo)>
		<!ELEMENT titulo (#PCDATA)>
		
	<!ELEMENT cuerpo (texto, marque)>
		<!ELEMENT texto (#PCDATA)>
		<!ELEMENT marque (#PCDATA)>
		
	<!ELEMENT pie (link1, link2)>
		<!ELEMENT link1 (#PCDATA)>
		<!ELEMENT link2 (#PCDATA)>

=== JuanjoSalva/P-gina-xsl/cgi-bin/BTT/HTML/HTML/INICIO/Inicio.xml
<?xml version="1.0" encoding ="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href= "Inicio.xsl"?>
<!DOCTYPE pagina SYSTEM "Inicio.dtd">
 
<pagina>
	<cabecera>
			<titulo>PEÑA APEDALES</titulo>
	</cabecera>
	
	<cuerpo>
		<texto>Este texto es de Bienvenida a al página</texto>
		<marque> y este otro una marquesina</marque>
	</cuerpo>
	
    <pie>		
		<link1>Registrarme</link1>
		<link2>Salir</link2>
	</pie>
</pagina>
