=== JuanjoSalva/P-gina-xsl/cgi-bin/BTT/HTML/HTML/CONTACTAR/Contactar.dtd
<!ELEMENT pagina (cabecera,cuerpo,pie)>
	<!ELEMENT cabecera (titulo)>
		<!ELEMENT titulo (#PCDATA)>
		
	<!ELEMENT cuerpo (nombre, telefono, correo)>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT telefono (#PCDATA)>
		<!ELEMENT correo (#PCDATA)>
	
	<!ELEMENT pie (link1, link2, boton)>
		<!ELEMENT link1 (#PCDATA)>
		<!ELEMENT link1 (#PCDATA)>
		<!ELEMENT boton (#PCDATA)>

=== JuanjoSalva/P-gina-xsl/cgi-bin/BTT/HTML/HTML/CONTACTAR/Contactar.xml
<?xml version="1.0" encoding ="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href= "Contactar.xsl"?>
<!DOCTYPE pagina SYSTEM "Contactar.dtd">
 
<pagina>
    
	
	<cabecera>
			<titulo>CONTACTO</titulo>
	</cabecera>
	
	<cuerpo>
		<nombre>Raúl Pérez</nombre>
		<telefono>645852434</telefono>
		<correo>Raul@gmail.com</correo>
	</cuerpo>
	
    <pie>
		<link1>Volver al Principio</link1>
		<link2>Inicio</link2>
		<boton>Contactar</boton>
	</pie>
</pagina>
