=== JuanjoSalva/P-gina-xsl/_vti_txt/HTML/HTML/MAPA/Mapa.dtd
<!ELEMENT pagina (titulo,cuerpo,pie)>
	<!ELEMENT titulo (#PCDATA)>
	<!ELEMENT cuerpo (calle,numero,piso,cp,telefono,foto)>
	<!ELEMENT calle (#PCDATA)>
	<!ELEMENT numero (#PCDATA)>
	<!ELEMENT piso (#PCDATA)>
	<!ELEMENT cp (#PCDATA)>
	<!ELEMENT telefono (#PCDATA)>
	<!ELEMENT mapa (#PCDATA)>
		
	<!ELEMENT pie (boton*)>
		<!ELEMENT boton (texto, ruta)>
			<!ELEMENT texto (#PCDATA)>
			<!ELEMENT ruta (#PCDATA)>

=== JuanjoSalva/P-gina-xsl/_vti_txt/HTML/HTML/MAPA/Mapa.xml
<?xml version="1.0" encoding ="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href= "Mapa.xsl"?>
<!DOCTYPE pagina SYSTEM "Mapa.dtd">
 
<pagina>
	<titulo> MAPA </titulo>
	<cuerpo>
		<calle>San Vicente</calle>
		<numero>26</numero>
		<piso>Local</piso>
		<cp>52354</cp>
		<telefono>625875432</telefono>
		<mapa>mapa.gif</mapa>
	</cuerpo>
	
    
</pagina>
